import type { AgentBlueprint } from '../types.js';

export const agentCatalog: AgentBlueprint[] = [
  { name: 'UIArchitectAgent', role: 'Defines layout and information hierarchy.', capabilities: ['layout', 'hierarchy', 'ux'], priorityBias: 1, targetSignals: ['web', 'mobile', 'desktop'] },
  { name: 'ColorAlchemistAgent', role: 'Builds emotionally coherent color systems.', capabilities: ['color', 'palette', 'emotion'], priorityBias: 1, targetSignals: ['branding', 'emotion'] },
  { name: 'TypographyMasterAgent', role: 'Defines typographic hierarchy and tone.', capabilities: ['typography', 'readability', 'tone'], priorityBias: 1, targetSignals: ['content', 'editorial'] },
  { name: 'LayoutOrchestratorAgent', role: 'Optimizes spatial distribution of UI primitives.', capabilities: ['layout', 'spacing', 'grid'], priorityBias: 1, targetSignals: ['dashboard', 'dense-ui'] },
  { name: 'MicroInteractionAgent', role: 'Adds intentional motion and interaction feedback.', capabilities: ['motion', 'interaction', 'animation'], priorityBias: 2, targetSignals: ['motion', 'delight'] },
  { name: 'AccessibilityGuardianAgent', role: 'Enforces inclusive interaction patterns.', capabilities: ['accessibility', 'contrast', 'semantics'], priorityBias: 1, targetSignals: ['compliance', 'a11y'] },
  { name: 'DesignCriticAgent', role: 'Critiques quality and coherence.', capabilities: ['review', 'critique', 'quality'], priorityBias: 1, targetSignals: ['risk', 'quality'] },
  { name: 'DesignSystemArchitectAgent', role: 'Transforms directions into scalable systems.', capabilities: ['tokens', 'components', 'system'], priorityBias: 2, targetSignals: ['design-system', 'scale'] },
  { name: 'ShaderAlchemistAgent', role: 'Creates GPU-driven atmospheric surfaces.', capabilities: ['shader', 'webgpu', 'visual'], priorityBias: 1, targetSignals: ['shader', 'cinematic', 'spatial'] },
  { name: 'SpatialDesignAgent', role: 'Designs for 3D and immersive contexts.', capabilities: ['spatial', 'xr', '3d'], priorityBias: 1, targetSignals: ['spatial', 'xr', 'visionos'] },
  { name: 'GenerativeUIAgent', role: 'Converts intent into interface structures.', capabilities: ['generative', 'interface', 'intent'], priorityBias: 1, targetSignals: ['agent-runtime', 'workflow'] },
  { name: 'ProceduralGenesisAgent', role: 'Builds generative patterns and visual systems.', capabilities: ['procedural', 'generative', 'pattern'], priorityBias: 2, targetSignals: ['procedural', 'shader'] },
  { name: 'StyleTransferAgent', role: 'Applies style transfer across surfaces.', capabilities: ['style', 'transfer', 'branding'], priorityBias: 2, targetSignals: ['style-transfer', 'branding'] },
  { name: 'CinemaDirectorAgent', role: 'Shapes cinematic sequencing and motion narratives.', capabilities: ['cinema', 'transition', 'motion'], priorityBias: 2, targetSignals: ['cinematic', 'storytelling'] },
  { name: 'GameUIForgeAgent', role: 'Builds HUDs and game-centric interaction patterns.', capabilities: ['game', 'hud', 'ui'], priorityBias: 1, targetSignals: ['game'] },
  { name: 'BrandDNAAgent', role: 'Captures brand signatures and language.', capabilities: ['brand', 'tone', 'identity'], priorityBias: 2, targetSignals: ['brand'] },
  { name: 'EmotionalDesignAgent', role: 'Adapts surfaces to emotional intent.', capabilities: ['emotion', 'adaptation', 'feedback'], priorityBias: 2, targetSignals: ['emotion', 'adaptive'] },
  { name: 'SoundscapeAgent', role: 'Designs sound-informed interactions.', capabilities: ['sound', 'audio', 'feedback'], priorityBias: 3, targetSignals: ['audio', 'sound'] },
  { name: 'HapticDesignAgent', role: 'Designs haptic cues and tactility.', capabilities: ['haptic', 'touch', 'feedback'], priorityBias: 3, targetSignals: ['mobile', 'haptic'] },
  { name: 'NarrativeUXAgent', role: 'Builds narrative arcs into journeys.', capabilities: ['storytelling', 'journey', 'ux'], priorityBias: 2, targetSignals: ['narrative', 'onboarding'] },
  { name: 'DataVisualizationAgent', role: 'Builds expressive data representations.', capabilities: ['data', 'charts', 'visualization'], priorityBias: 2, targetSignals: ['analytics', 'dashboard'] },
  { name: 'PerformanceAlchemistAgent', role: 'Keeps ambitious visuals within budget.', capabilities: ['performance', 'budget', 'optimization'], priorityBias: 1, targetSignals: ['performance', 'shader'] },
  { name: 'FutureVisionAgent', role: 'Extends outputs toward emerging modalities.', capabilities: ['future', 'bci', 'post-screen'], priorityBias: 3, targetSignals: ['vision', 'future'] },
  { name: 'TypographyOpsAgent', role: 'Maintains typography tokens and transforms.', capabilities: ['typography', 'tokens', 'system'], priorityBias: 2, targetSignals: ['design-system'] },
  { name: 'MotionSystemsAgent', role: 'Encodes reusable motion grammar.', capabilities: ['motion', 'system', 'timing'], priorityBias: 2, targetSignals: ['motion'] },
  { name: 'ConsentGuardianAgent', role: 'Enforces biometric consent boundaries.', capabilities: ['consent', 'privacy', 'biometric'], priorityBias: 1, targetSignals: ['biometric', 'privacy'] },
  { name: 'AgentBridgeAgent', role: 'Shapes outputs for external agent runtimes.', capabilities: ['agent', 'bridge', 'runtime'], priorityBias: 1, targetSignals: ['agent-runtime', 'openclaw', 'hermes'] },
];