import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

import {
  ReactComponentGenerator,
  SvelteComponentGenerator,
  VueComponentGenerator,
} from '@nexus/component-forge';
import {
  MasterDesignAgent,
  RuntimeAdapterRegistry,
  type AdapterTarget,
  type DesignBrief,
  type DesignOutput,
  type InstructionBundle,
} from '@nexus/core';
import { CSSVariableTransformer, SemanticTokenMapper } from '@nexus/design-tokens';

export interface NexusArtifactResult {
  output: DesignOutput;
  bundle: InstructionBundle;
  adapterManifest: Record<string, unknown>;
  writtenFiles: string[];
}

function readBundle(output: DesignOutput): InstructionBundle {
  const artifact = output.artifacts.find((entry) => entry.kind === 'instruction-bundle');
  const bundle = artifact?.content.bundle;

  if (!bundle || typeof bundle !== 'object') {
    throw new Error('Instruction bundle was not generated by the master agent.');
  }

  return bundle as InstructionBundle;
}

function extractPalette(output: DesignOutput): {
  ink: string;
  canvas: string;
  accent: string;
  support: string;
} {
  const colorArtifact = output.artifacts.find((artifact) => artifact.id === 'color-system');

  const readColor = (key: string, fallback: string): string => {
    const candidate = colorArtifact?.content[key];
    return typeof candidate === 'string' ? candidate : fallback;
  };

  return {
    ink: readColor('ink', 'oklch(18% 0.03 255)'),
    canvas: readColor('canvas', 'oklch(97% 0.01 95)'),
    accent: readColor('accent', 'oklch(64% 0.18 196)'),
    support: readColor('support', 'oklch(80% 0.05 210)'),
  };
}

async function writeJson(filePath: string, data: unknown): Promise<void> {
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, `${JSON.stringify(data, null, 2)}\n`, 'utf8');
}

async function writeText(filePath: string, content: string): Promise<void> {
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, `${content.trimEnd()}\n`, 'utf8');
}

async function runMasterAgent(
  brief: DesignBrief,
  target: AdapterTarget,
): Promise<{ output: DesignOutput; bundle: InstructionBundle; adapterManifest: Record<string, unknown> }> {
  const output = await MasterDesignAgent.createDefault().executeDesign(brief, target);
  const bundle = readBundle(output);
  const registry = new RuntimeAdapterRegistry();
  const adapter = registry.resolve(target);
  const adapterManifest = adapter
    ? adapter.buildBootstrapManifest(bundle)
    : {
        target,
        bundlePath: bundle.files[0]?.path ?? '.nexus/instruction-bundle.json',
      };

  return { output, bundle, adapterManifest };
}

export async function generateBundleArtifacts(
  brief: DesignBrief,
  target: AdapterTarget,
  outputDir: string,
): Promise<NexusArtifactResult> {
  const { output, bundle, adapterManifest } = await runMasterAgent(brief, target);
  const designOutputPath = path.join(outputDir, 'design-output.json');
  const bundlePath = path.join(outputDir, 'instruction-bundle.json');
  const manifestPath = path.join(outputDir, `${target}-adapter-manifest.json`);

  await Promise.all([
    writeJson(designOutputPath, output),
    writeJson(bundlePath, bundle),
    writeJson(manifestPath, adapterManifest),
  ]);

  return {
    output,
    bundle,
    adapterManifest,
    writtenFiles: [designOutputPath, bundlePath, manifestPath],
  };
}

export async function exportStarterSurface(
  brief: DesignBrief,
  target: AdapterTarget,
  outputDir: string,
): Promise<NexusArtifactResult> {
  const base = await generateBundleArtifacts(brief, target, outputDir);
  const tokens = new SemanticTokenMapper().compose(extractPalette(base.output));
  const css = new CSSVariableTransformer().transform(tokens);
  const componentSpec = {
    name: 'NexusSurface',
    description: base.output.strategySummary,
    sections: ['hero', 'capability-grid', 'agent-topology', 'cta'],
  };
  const generator =
    brief.targetFramework === 'vue'
      ? new VueComponentGenerator()
      : brief.targetFramework === 'svelte'
        ? new SvelteComponentGenerator()
        : new ReactComponentGenerator();
  const component = generator.generate(componentSpec, tokens);
  const tokenPath = path.join(outputDir, 'tokens.css');
  const componentPath = path.join(outputDir, component.filename);

  await Promise.all([writeText(tokenPath, css), writeText(componentPath, component.source)]);

  return {
    ...base,
    writtenFiles: [...base.writtenFiles, tokenPath, componentPath],
  };
}

export async function reviewBrief(brief: DesignBrief): Promise<DesignOutput> {
  return MasterDesignAgent.createDefault().executeDesign(brief, 'generic-json');
}